# Generated by Django 5.2 on 2025-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productpage_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='personalized',
            field=models.BooleanField(default=True),
        ),
    ]
