# Generated by Django 5.2 on 2025-05-11 10:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productpage_personalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='widgets',
            field=wagtail.fields.StreamField([('product_images', 1), ('product_options', 4), ('customer_reviews', 9)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('product_attribute_key', 2), ('product_attribute_values', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 6: ('wagtail.blocks.IntegerBlock', (), {'required': True}), 7: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('name', 2), ('comments', 5), ('ratting_given', 6), ('customer_verified', 7), ('customer_location', 2)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {})}, null=True),
        ),
    ]
