# Generated by Django 5.2 on 2025-05-11 19:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productpage_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='widgets',
            field=wagtail.fields.StreamField([('product_images', 1), ('product_options', 4), ('trending', 7), ('customer_reviews', 12)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('product_attribute_key', 2), ('product_attribute_values', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 2), ('pages', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 9: ('wagtail.blocks.IntegerBlock', (), {'required': True}), 10: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('name', 2), ('comments', 8), ('ratting_given', 9), ('customer_verified', 10), ('customer_location', 2)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {})}, null=True),
        ),
    ]
