# Generated by Django 5.2 on 2025-05-13 18:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productpagetag_productpage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='widgets',
            field=wagtail.fields.StreamField([('product_images', 1), ('product_options', 4), ('trending', 7), ('synod', 8), ('customer_reviews', 13)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('product_attribute_key', 2), ('product_attribute_values', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 2), ('pages', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('heading', 2), ('tag', 2)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 10: ('wagtail.blocks.IntegerBlock', (), {'required': True}), 11: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('name', 2), ('comments', 9), ('ratting_given', 10), ('customer_verified', 11), ('customer_location', 2)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {})}, null=True),
        ),
    ]
