# Generated by Django 5.2 on 2025-05-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productpage_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='stock_available',
            field=models.BooleanField(default=True),
        ),
    ]
