# Generated by Django 5.2 on 2025-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productpage_stock_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='mrp',
            field=models.IntegerField(default=300),
        ),
    ]
