# Generated by Django 5.2 on 2025-05-02 09:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('footer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='widgets',
            field=wagtail.fields.StreamField([('carousel_image', 1), ('product_search', 2), ('personalised_category', 4), ('trending', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.BooleanBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('heading', 3), ('category_image', 1)]], {}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('price', 3), ('card_image', 0)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 3), ('card', 6)]], {})}, null=True),
        ),
    ]
