# Generated by Django 5.2 on 2025-05-04 10:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rawhtml_homepage_body_homepage_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='widgets',
            field=wagtail.fields.StreamField([('carousel_image', 1), ('product_search', 2), ('personalised_category', 4), ('trending', 7), ('html_panels', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.BooleanBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('heading', 3), ('category_image', 1)]], {}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('price', 3), ('card_image', 0)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 3), ('card', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'required': True})}, null=True),
        ),
    ]
