# Generated by Django 5.2 on 2025-05-13 08:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='widgets',
            field=wagtail.fields.StreamField([('carousel_image', 1), ('product_search', 2), ('personalised_category', 7), ('trending', 9), ('synod', 10), ('html_panels', 11)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.BooleanBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': True}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('picture', 0), ('pages', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 3), ('category_image', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (4,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 3), ('pages', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 3), ('tag', 3)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'required': True})}, null=True),
        ),
    ]
